name: Build Check

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

env:
    CARGO_TERM_COLOR: always

jobs:
    build-and-test:
        name: Build and Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Rust
              uses: dtolnay/rust-toolchain@stable
              with:
                  components: rustfmt, clippy

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Check formatting
              run: cargo fmt --all -- --check

            - name: Run Clippy
              run: cargo clippy --all-targets --all-features --workspace -- -D warnings

            - name: Build
              run: cargo build --verbose --all --all-features

            - name: Run tests
              run: cargo test --verbose --all --all-features
