name: Build and Release

on:
  push:
    tags:
      - "v*" # 每次打 tag 时触发，比如 v0.1.0

jobs:
  build:
    name: Build binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare artifact
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/peeko dist/
          cd dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            zip peeko-${{ matrix.target }}.zip peeko.exe
          else
            tar czf peeko-${{ matrix.target }}.tar.gz peeko
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: peeko-${{ matrix.target }}
          path: dist/
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
